### PR TITLE
Try new pr

### PR DESCRIPTION
**Pull request by stevepeak**
Just trying this new concept. No need to merge atm. Thanks

### CODE REVIEW

**Comment by stevepeak** [comment]
@jfalcou not sure why that build failed... 

```bash
$ if [[ ${CC} = gcc ]]; then bash <(curl -o https://raw.githubusercontent.com/codecov/codecov-bash/fixcat/codecov) fi
/home/travis/build.sh: eval: line 42: syntax error: unexpected end of file
```

I don't think there is a parse error in the changes on https://github.com/codecov/codecov-bash/pull/5

**Comment by jfalcou** [comment]
Looks like the last attempt uploaded some coverage here : 

http://codecov.io/github/NumScale/nstest?ref=89dca94c891320d2e7ca65791a2d98dabb87609c

but I can't acces it from my repository page on codecov. Similarly, the coverage loading in the web plugin don't give anything. Should I merge this PR to get the proper behavior ?

**Comment by stevepeak** [comment]
Can you restart a previous build (or make an empty commit) to submit reports on your end. This issue has been fixed. I'll checkout the plugin issue too. Thanks!

**Comment by jfalcou** [comment]
This appeared : https://codecov.io/github/NumScale/nstest?branch=features/codecov_support
So I guess we're set. Next step for me is probably pruning more stuff as i don't care about /usr/include and boost-trunk.

**Comment by jfalcou** [comment]
Which means maybe rebase those three commits into a single one and I merge this baby

**Comment by stevepeak** [comment]
Don't worry about the merge of this request. Keep the original methods you are using now :)

**Comment by jfalcou** [comment]
Ok perfect.
Last point, I'm pruning the coverage info to remove system and boost header but apparently they still appear in my codecov report. Is there something I'm missing ?

**Comment by stevepeak** [comment]
Are you trying to ignore certain files and/or folders (like the `tests/*`)? Checkout the **Features -> Ignore Files** (or [click here](https://codecov.io/github/NumScale/nstest/features/ignore)) and add in `tests/*` into the ignore files list.

**Comment by jfalcou** [comment]
Perfect :D

**Pull request closed without merging**
